### ISSUE TITLE
Не работает тег noscript

### ISSUE THREAD

**Issue by laits** [paradoxfm/firefox_njs#1]
Здравствуйте сразу скажу спасибо за расширение так как нужно тестировать сайт с выключенным js понадобилось быстро включать  выключать js через конфиг не удобно нашёл Ваше.
Заметил небольшую ошибку при выключеном  js не отображает тег
'noscript' '/noscript' к примеру так не работает

'noscript'Ваш браузер не поддерживает скрипты!'/noscript' 

если отключить через конфиг в браузере или через расширение NoScript то всё правильно работает.

**Comment by paradoxfm** [comment]
это вам надо в about:config поменять настройку javascript.enabled
